// Science jokes for the "Joke of the day" box on the home page.
// Each joke is { q: 'the set-up', a: 'the punchline' }. The punchline stays hidden until
// the student presses "Reveal the answer". A different joke is picked on each page load.
// To add a joke, copy a line and change the words. Keep them school-safe.
window.JOKES = [
  // ----- Mechanics -----
  { q: 'What did Newton say when an apple hit him on the head?', a: '"That\'s gravity for you. It really gets me down."' },
  { q: 'What do you call a stationary object that refuses to move?', a: 'Stubborn. Physicists call it inertia.' },
  { q: 'How do you know a car has a lot of inertia?', a: 'It takes a lot of force to change its mind.' },
  { q: 'Why did the box refuse to slide down the slope?', a: 'It was experiencing too much friction in its life.' },
  { q: 'What did the friction force say to the moving block?', a: '"I\'m always against you, but it\'s nothing personal."' },
  { q: 'Why was the pendulum always late?', a: 'It kept swinging by other places first.' },
  { q: 'What is a physicist\'s favourite way to travel?', a: 'By momentum. Once they get going, it\'s hard to stop them.' },
  { q: 'Why did the ball stop rolling?', a: 'It ran out of energy… sorry, it transferred its energy to thermal stores.' },
  { q: 'What did one rope say to the other at the top of the hill?', a: '"I\'m under a lot of tension today."' },
  { q: 'What do you call a car that moves in a perfect circle at constant speed?', a: 'Accelerating. Don\'t let anyone tell you otherwise.' },
  { q: 'Why did the satellite never get lost?', a: 'It always stayed in its own orbit.' },
  { q: 'Why don\'t physicists ever argue about free fall?', a: 'They all come down on the same side in the end.' },
  { q: 'What did the skydiver say at terminal velocity?', a: '"Finally, a balanced life."' },
  { q: 'Why did the projectile do so well in its exams?', a: 'It followed a perfectly predictable path.' },
  { q: 'What did the vector say to the scalar?', a: '"You have no sense of direction."' },
  { q: 'Why did the scalar feel lost?', a: 'It had magnitude but no direction in life.' },
  { q: 'What is the most moving part of a physics lesson?', a: 'The displacement. The distance was a bit longer.' },
  { q: 'Why was the speedometer so calm?', a: 'It only ever dealt with the instant.' },
  { q: 'What did the velocity–time graph say about its area?', a: '"It\'s where I keep all my displacement."' },
  { q: 'Why did the student draw a tangent on the curve?', a: 'They wanted to get to the point.' },
  { q: 'Why did the lift feel so heavy on the way up?', a: 'It was having an uplifting experience, and the normal force went up too.' },
  { q: 'What did Newton\'s third law say to the wall?', a: '"Push me and I\'ll push you right back."' },
  { q: 'What do you get if you cross a rocket with Newton\'s third law?', a: 'Lift-off. Every action has an equal and opposite reaction.' },
  { q: 'Why was the spring always so positive?', a: 'No matter how far it was pushed, it always bounced back.' },
  { q: 'What did the spring say after being stretched too far?', a: '"I\'ve gone past my limit of proportionality and I\'m not the same any more."' },
  { q: 'Why did the iceberg get the job?', a: 'It had excellent buoyancy and kept its head above water.' },
  { q: 'What did the centripetal force say to the car?', a: '"Stick with me and we\'ll go round together."' },
  { q: 'Why is there no centrifugal force at a physics party?', a: 'It was never really there in the first place.' },

  { q: 'Why did the student do momentum homework all night?', a: 'Once they got going, nothing could stop them.' },

  // ----- Energy and power -----
  { q: 'Why did the physicist love their job?', a: 'It gave them so much potential.' },
  { q: 'What did the ball at the top of the hill say?', a: '"I\'ve got so much potential."' },
  { q: 'How did the ball at the bottom of the hill feel?', a: 'Full of kinetic energy and ready to go.' },
  { q: 'Why couldn\'t the energy be destroyed?', a: 'It knew how to transfer to another store.' },
  { q: 'What did the student say when told energy can\'t be created?', a: '"That explains why I have none on Monday mornings."' },
  { q: 'Why was the machine so honest?', a: 'It was always open about its efficiency.' },
  { q: 'What do you call a machine that is 100% efficient?', a: 'Imaginary.' },
  { q: 'What is a Sankey diagram\'s favourite saying?', a: '"It all adds up in the end."' },
  { q: 'Why did the power station get promoted?', a: 'It worked hard, and fast.' },
  { q: 'Why did the battery go to therapy?', a: 'It had too many unresolved charges.' },
  { q: 'What is a joule\'s favourite jewellery?', a: 'Jewels. Obviously.' },
  { q: 'What did the watt say to the joule?', a: '"You\'re fine, but I get things done every second."' },
  { q: 'Why did the light bulb fail its exam?', a: 'It wasn\'t very bright.' },

  // ----- Thermal physics and gases -----
  { q: 'Why did the thermometer go to university?', a: 'It wanted to get more degrees.' },
  { q: 'What did the thermodynamics student say when asked to tidy up?', a: '"I can\'t. Entropy always increases."' },
  { q: 'Why do physicists never have messy rooms?', a: 'They do. They just call it high entropy.' },
  { q: 'How did the gas molecule feel after hitting the wall?', a: 'Under a lot of pressure.' },
  { q: 'Why did the balloon refuse to go to the cold party?', a: 'It knew it would shrink under the pressure.' },
  { q: 'What did Boyle say when you squeezed his gas?', a: '"Pressure\'s up, volume\'s down. It\'s the law."' },
  { q: 'Why are ideal gases so popular?', a: 'They never have any attractions to deal with.' },
  { q: 'Why did the ice cube go to school?', a: 'It wanted to change its state of mind.' },
  { q: 'What did the steam say to the ice?', a: '"You need to loosen up and let off some latent heat."' },
  { q: 'Why is the greenhouse effect so popular with plants?', a: 'It keeps things nice and warm.' },

  // ----- Electricity -----
  { q: 'What did the voltmeter say to the ammeter?', a: '"I\'ll be in parallel. You go in series."' },
  { q: 'Why was the resistor always in trouble?', a: 'It resisted everything the teacher said.' },
  { q: 'What did the electron say to the resistor?', a: '"Ohm my goodness, you\'re in the way."' },
  { q: 'What is a resistor\'s favourite place to relax?', a: 'Ohm sweet ohm.' },
  { q: 'Why did the student get an electric shock from the joke?', a: 'It was a current event.' },
  { q: 'Why did the electricity bill look so serious?', a: 'It was just being current.' },
  { q: 'What did one electron say to the other at the junction?', a: '"Let\'s split up. We\'ll meet again on the other side."' },
  { q: 'Why did the circuit go to the doctor?', a: 'It had a short.' },
  { q: 'How do you make a resistor happy?', a: 'Give it some potential difference.' },
  { q: 'Why did the cell go to the party?', a: 'It was fully charged and ready.' },
  { q: 'Why was the lightning bolt so good at maths?', a: 'It always took the shortest path to the answer.' },
  { q: 'What do you call a group of electrons that move in step?', a: 'A current affair.' },
  { q: 'Why was the wire never lonely?', a: 'It was always surrounded by a magnetic field of friends.' },

  // ----- Waves, sound and light -----
  { q: 'Why do waves never get tired?', a: 'They transfer energy, not matter. So they never carry anything heavy.' },
  { q: 'What did the sea say to the shore?', a: 'Nothing. It just waved.' },
  { q: 'Why did the sound wave go to the doctor?', a: 'It was having trouble with its pitch.' },
  { q: 'What do you call a sound wave that can\'t make up its mind?', a: 'A standing wave.' },
  { q: 'Why couldn\'t the astronaut hear the explosion in space?', a: 'There was no medium to pass on the news.' },
  { q: 'What did the photon say at airport check-in?', a: '"No luggage, thanks. I\'m travelling light."' },
  { q: 'Why did the light ray fail the exam?', a: 'It kept getting refracted from the right answer.' },
  { q: 'Why did the light ray bend when it entered the water?', a: 'It slowed down to enjoy the view.' },
  { q: 'Why did the ray of light stay inside the optical fibre?', a: 'It was totally internally reflecting on its life choices.' },
  { q: 'What did the mirror say to the student?', a: '"I see your point. In fact, I reflect on it."' },
  { q: 'Why was the diffraction grating so popular?', a: 'It always made a spectacle of itself.' },
  { q: 'Why did the wave go to the slit?', a: 'It wanted to spread out a bit.' },
  { q: 'What did the two waves say when they met in phase?', a: '"Together we\'re so much greater."' },
  { q: 'What did the two waves say when they met out of phase?', a: 'Nothing. They cancelled each other out.' },
  { q: 'Why did the ambulance sound different on the way back?', a: 'It was going through a Doppler phase.' },
  { q: 'What is the Doppler effect\'s favourite song?', a: 'Anything that changes pitch as it goes past.' },
  { q: 'Why did the laser go to school?', a: 'It wanted to be more focused and coherent.' },
  { q: 'What do you call a dinosaur that studies light?', a: 'A spectro-saurus.' },

  // ----- Fields, astrophysics and gravity -----
  { q: 'Why did the magnet fail the exam?', a: 'It was too attracted to the wrong answers.' },
  { q: 'What did the north pole say to the other north pole?', a: '"Go away, you\'re so repulsive."' },
  { q: 'Why do astronomers go to bed so late?', a: 'They need to see the stars.' },
  { q: 'How do you organise a party in space?', a: 'You planet.' },
  { q: 'Why did the Sun go to school?', a: 'To get a little brighter.' },
  { q: 'Why did the Moon skip dinner?', a: 'It was already full.' },
  { q: 'What kind of music do planets listen to?', a: 'Neptunes.' },
  { q: 'Why is a black hole like a bad teacher?', a: 'Once your homework goes in, you never get it back.' },
  { q: 'Why did the astronaut take a ruler into space?', a: 'To measure the light years.' },
  { q: 'What is a light year?', a: 'Like a normal year, but with fewer calories.' },
  { q: 'Why did the comet get a bad report?', a: 'It kept going off on tangents.' },
  { q: 'Why did gravity get the job?', a: 'It had a very strong pull in the interview.' },
  { q: 'What did the Earth say to the Moon?', a: '"Stop going round in circles and come and see me."' },

  // ----- Atoms, quantum and nuclear -----
  { q: 'Why can\'t you trust atoms?', a: 'They make up everything.' },
  { q: 'An atom says, "I\'ve lost an electron." Its friend asks, "Are you sure?"', a: '"Yes, I\'m positive."' },
  { q: 'Why was the proton so cheerful?', a: 'It always stayed positive.' },
  { q: 'Why did the neutron get into the concert for free?', a: 'There was no charge.' },
  { q: 'What did the nucleus say to the electron?', a: '"Stop running around and come closer."' },
  { q: 'Why did the electron get kicked out of the library?', a: 'It kept jumping between levels.' },
  { q: 'What did the photon say when it was asked to slow down?', a: '"Sorry, I only have one speed in a vacuum."' },
  { q: 'Why did Heisenberg never get lost?', a: 'He always knew exactly where he was. He just had no idea how fast he was going.' },
  { q: 'Schrödinger\'s cat walks into a room… or does it?', a: 'Nobody knows until somebody opens the door.' },
  { q: 'What is a quantum physicist\'s favourite subject at school?', a: 'All of them, until you check their timetable.' },
  { q: 'Why was the radioactive nucleus so calm?', a: 'It knew how to let things go, one half-life at a time.' },
  { q: 'Why was the uranium nucleus so tired?', a: 'It was always splitting itself in two.' },
  { q: 'What did the two hydrogen nuclei say in the Sun?', a: '"Let\'s get together. It\'s going to be fusion."' },
  { q: 'What did the alpha particle say to the paper?', a: '"You stopped me in my tracks."' },
  { q: 'What did the gamma ray say to the sheet of paper?', a: '"See you later. I\'m going straight through."' },

  // ----- Units, measurement and scientists -----
  { q: 'Why did the student bring a ladder to the physics lesson?', a: 'The teacher said they were moving on to higher-level physics.' },
  { q: 'Why did the student get full marks for their uncertainty?', a: 'They were absolutely sure about it… ± a bit.' },
  { q: 'What did the significant figure say to the zero in front of it?', a: '"You don\'t count."' },
  { q: 'How many physicists does it take to change a light bulb?', a: 'Two. One to hold the bulb and one to rotate the universe.' },
  { q: 'What do physicists enjoy doing most at sports events?', a: 'The wave.' },
  { q: 'What did Einstein say to the clock?', a: '"It\'s all relative."' },
  { q: 'Why did Einstein never get bored on the train?', a: 'From his point of view, the platform was the one moving.' },
  { q: 'What did the metre say to the centimetre?', a: '"You\'re a hundred times smaller, but I still look up to you."' },
  { q: 'Why is the speed of light so fast?', a: 'It has nowhere to stop for a snack.' },
  { q: 'What do you call an educated tube?', a: 'A graduated cylinder.' },
  { q: 'What did the graph say to the student who forgot the axis labels?', a: '"I have no idea who I am."' },
  { q: 'Why was the straight-line graph so confident?', a: 'It had a constant gradient and passed through the origin.' },
  { q: 'Why did the teacher wear sunglasses during the optics lesson?', a: 'The class was so bright.' },
];
