// Science jokes for the "Joke of the day" box on the home page.
// Each joke is { q: 'the set-up', a: 'the punchline' }. The punchline stays hidden until
// the student presses "Reveal the answer". A different joke is picked on each page load.
// These are well-known published jokes, collected from science-joke lists such as
// Reader's Digest, Science Kids, LaffGaff, Puzzle Prime, Bucknell University's physics
// department, Jupiter Scientific and Fun Kids Jokes. Only school-safe ones are included.
// To add a joke, copy a line and change the words.
window.JOKES = [
  // ----- Mechanics and gravity -----
  { q: 'Why can\'t you trust an atom?', a: 'They make up everything.' },
  { q: 'Have you heard about the book on anti-gravity?', a: 'It\'s impossible to put down.' },
  { q: 'Why is it so hard to get out of bed in the morning?', a: 'Newton\'s first law: a body at rest wants to stay at rest.' },
  { q: 'Why didn\'t Isaac Newton dodge the falling apple?', a: 'He didn\'t understand the gravity of the situation.' },
  { q: 'Why did Isaac Newton invent calculus?', a: 'He wanted to differentiate himself.' },
  { q: 'I told my physics teacher a joke about inertia.', a: 'It didn\'t move them.' },
  { q: 'Two cats of the same size slide down a roof at the same time, but one falls off first. Which one?', a: 'The one with the smaller "mew" (μ, the coefficient of friction).' },
  { q: 'Why is it best to teach physics on the edge of a cliff?', a: 'That\'s where the students have the most potential.' },
  { q: 'What do you get when you cross a chicken with a turkey?', a: '(Chicken)(turkey) sin θ.' },
  { q: 'What do you get when you cross a chicken with a rock climber?', a: 'You can\'t. A rock climber is a scalar.' },
  { q: 'According to Einstein, why did the chicken cross the road?', a: 'Whether the chicken crossed the road or the road moved beneath the chicken depends on your frame of reference.' },
  { q: 'A bar walks into a man…', a: 'Oops, wrong frame of reference.' },
  { q: 'Why did the scarecrow become a successful physicist?', a: 'He was outstanding in his field.' },
  { q: 'What do physicists enjoy doing most at sports matches?', a: 'The wave.' },
  { q: 'What did the duck say to the physicist?', a: 'Quark, quark, quark!' },

  // ----- Energy and thermal physics -----
  { q: 'You matter…', a: '…unless you multiply yourself by the speed of light squared. Then you energy.' },
  { q: 'Why does a burger have less energy than a steak?', a: 'It\'s in its ground state.' },
  { q: 'Why did the atom get promoted?', a: 'It had potential.' },
  { q: 'What do you call someone who steals energy?', a: 'A joule thief.' },
  { q: 'Why did the thermometer go to school?', a: 'To get more degrees.' },
  { q: 'What did the thermometer say to the graduated cylinder?', a: '"You may have graduated, but I\'ve got more degrees."' },
  { q: 'Why did the thermometer go on a diet?', a: 'It wanted to lose a couple of degrees.' },
  { q: 'What did the physicist say when asked why they were sitting on the sofa all day?', a: '"I\'m not lazy. I\'m in thermal equilibrium."' },
  { q: 'Have you heard the latest news about entropy?', a: 'It isn\'t what it used to be.' },

  // ----- Electricity and magnetism -----
  { q: 'Why can\'t you take electricity to a party?', a: 'It doesn\'t know how to conduct itself.' },
  { q: 'Why is electricity an ideal citizen?', a: 'Because it conducts itself so well.' },
  { q: 'Who solves mysteries involving electricity?', a: 'Sherlock Ohms.' },
  { q: 'Did you hear the joke about the resistor?', a: 'I was going to tell it, but I couldn\'t resist.' },
  { q: 'Why do electricians make great philosophers?', a: 'They\'re always thinking about current issues.' },
  { q: 'I finally got rid of the electric charge I\'d been carrying around.', a: 'Now I\'m ex-static!' },
  { q: 'What is a magnet\'s favourite sport?', a: 'Pole vaulting.' },
  { q: 'What did one electron say to the other?', a: '"Don\'t get excited. You\'ll only get into a state."' },

  // ----- Waves, light and sound -----
  { q: 'Why didn\'t the photon check in any luggage at the hotel?', a: 'It was travelling light.' },
  { q: 'Where does bad light end up?', a: 'In prism.' },
  { q: 'How does a photon say goodbye?', a: 'It waves.' },
  { q: 'What did one photon say to the other?', a: '"I\'m sick and tired of your interference."' },
  { q: 'Why does light travel faster than sound?', a: 'So that some people seem bright until you hear them speak.' },
  { q: 'What did the ocean say to the shore?', a: 'Nothing. It just waved.' },
  { q: 'Why is the ocean so salty?', a: 'Because the land never waves back.' },
  { q: 'Why did the echo feel lonely?', a: 'It kept repeating itself.' },
  { q: 'Why did the sound waves stop talking to each other?', a: 'They just couldn\'t find the same frequency any more.' },

  // ----- Atoms, quantum and nuclear -----
  { q: 'A sodium atom says to its friend, "I think I\'ve lost an electron." "Are you sure?"', a: '"Yes, I\'m positive."' },
  { q: 'A neutron walks in and asks how much a drink costs.', a: 'The waiter says, "For you, no charge."' },
  { q: 'Did you hear about the neutron that was arrested?', a: 'It was released without charge.' },
  { q: 'Why does the neutron only hang out with the proton, and never the electron?', a: 'The electron is far too negative.' },
  { q: 'What happens when electrons lose their energy?', a: 'They get Bohr-ed.' },
  { q: 'What did the proton say to the electron?', a: '"Stop being so negative!"' },
  { q: 'What\'s the most frightening word in nuclear physics?', a: '"Oops."' },
  { q: 'Did you hear about the man who was cooled to absolute zero?', a: 'He\'s 0 K now.' },
  { q: 'What did one uranium-238 nucleus say to the other?', a: '"Gotta split!"' },
  { q: 'What is a nuclear physicist\'s favourite lunch?', a: 'Fission chips.' },
  { q: 'What did the physicist say when they found two isotopes of helium?', a: '"HeHe!"' },
  { q: 'A Higgs boson walks into a church. The priest says, "We don\'t allow Higgs bosons in here."', a: 'The Higgs boson replies, "But without me, how can you have mass?"' },
  { q: 'A quantum physicist walks into a café…', a: '…or maybe they don\'t.' },
  { q: 'Schrödinger\'s cat walks into a room…', a: '…and doesn\'t.' },
  { q: 'Heisenberg is pulled over for speeding. The police officer asks, "Do you know how fast you were going?"', a: '"No, but I know exactly where I am."' },

  // ----- Relativity and physicists -----
  { q: 'Einstein developed a theory about space.', a: 'And it was about time, too.' },
  { q: 'How many theoretical physicists does it take to change a light bulb?', a: 'Two. One to hold the bulb and one to rotate the universe.' },
  { q: 'How many physicists does it take to change a light bulb?', a: 'Eleven. One to do it and ten to co-author the paper.' },
  { q: 'How many Heisenbergs does it take to change a light bulb?', a: 'If you know how many, you don\'t know where the light bulb is.' },
  { q: 'How many astronomers does it take to change a light bulb?', a: 'None. Astronomers prefer the dark.' },
  { q: 'Why did the physics teacher break up with the biology teacher?', a: 'There was no chemistry.' },

  // ----- Space and astronomy -----
  { q: 'How do you organise a party in space?', a: 'You planet.' },
  { q: 'Why did the Moon skip dinner?', a: 'It was already full.' },
  { q: 'Why did the Sun go to school?', a: 'To get brighter.' },
  { q: 'What did Mars say to Saturn?', a: '"Give me a ring sometime!"' },
  { q: 'How does the Moon cut its hair?', a: 'Eclipse it.' },
  { q: 'Why did the cow go to outer space?', a: 'To see the Milky Way.' },
  { q: 'How do astronauts serve dinner?', a: 'On flying saucers.' },
  { q: 'Have you heard about the new restaurant on the Moon?', a: 'The food is great, but there\'s no atmosphere.' },
  { q: 'What does a star win in a competition?', a: 'A constellation prize.' },
  { q: 'When do astronauts eat their lunch?', a: 'At launch time.' },
  { q: 'What do you call a sleepy planet?', a: 'Nap-tune.' },
  { q: 'Why did the astronaut break up with the Moon?', a: 'They needed space.' },
  { q: 'How do you get a baby to sleep in space?', a: 'You rocket.' },
  { q: 'Where do astronauts park their spaceships?', a: 'At a parking meteor.' },
  { q: 'Which key on the keyboard do astronauts use most?', a: 'The space bar.' },
  { q: 'Why did the rocket laugh?', a: 'It had a blast.' },
  { q: 'Why can\'t aliens play golf in space?', a: 'Too many black holes.' },
  { q: 'Why did the black hole go on a diet?', a: 'It had too much mass.' },
  { q: 'What is a light year?', a: 'The same as a normal year, but with fewer calories.' },
  { q: 'What kind of music do planets sing?', a: 'Neptunes.' },
  { q: 'What do you call a tick on the Moon?', a: 'A luna-tick.' },
  { q: 'How does the Solar System hold up its trousers?', a: 'With an asteroid belt.' },
  { q: 'How do you know when the Moon is running out of money?', a: 'It\'s down to its last quarter.' },
  { q: 'Why didn\'t the Dog Star laugh at the joke?', a: 'It was too Sirius.' },
  { q: 'What do you call a funny star?', a: 'A giggle-nova.' },
  { q: 'What did the alien say to the garden?', a: '"Take me to your weeder."' },
  { q: 'Why do astronauts never feel hungry after take-off?', a: 'They\'ve just had a big launch.' },

  // ----- Chemistry, biology and Earth science (for a change of scene) -----
  { q: 'I told a chemistry joke…', a: '…but there was no reaction.' },
  { q: 'What do you do with a sick chemist?', a: 'If you can\'t helium and you can\'t curium, you might as well barium.' },
  { q: 'Why did the noble gas cry?', a: 'All its friends Argon.' },
  { q: 'What do you call iron that laughs?', a: 'Fe-larious.' },
  { q: 'What is a chemist\'s favourite dog?', a: 'A lab.' },
  { q: 'Which fruit contains barium and two sodium atoms?', a: 'A BaNaNa.' },
  { q: 'What did Batman\'s theme tune sound like in the chemistry lab?', a: 'NaNaNaNaNaNaNaNa… Batman!' },
  { q: 'Why are chemists so good at solving problems?', a: 'They have all the solutions.' },
  { q: 'What do you call a tooth in a glass of water?', a: 'A one-molar solution.' },
  { q: 'Why did the white bear dissolve in water?', a: 'It was polar.' },
  { q: 'What kind of fish is made of two sodium atoms?', a: '2 Na.' },
  { q: 'What do you call an acid with a bad attitude?', a: 'A mean-o acid.' },
  { q: 'What do you call an educated tube?', a: 'A graduated cylinder.' },
  { q: 'How does a scientist freshen their breath?', a: 'With experi-mints.' },
  { q: 'Why did the germ cross the microscope?', a: 'To get to the other slide.' },
  { q: 'What did one tectonic plate say when it bumped into the other?', a: '"Sorry, my fault."' },
  { q: 'What did the cell say when its sister stepped on its foot?', a: '"Mitosis!"' },
];
