// The safeguard index: every rule future Paper 1B datasets inherit automatically (docs/PAPER1B_SPECIFICATION.md section 21),
// with the error codes that enforce it and the tests that prove it is enforced.
// test.mjs checks that every code here is the expected failure of at least one deliberately broken dataset
// (fixtures/broken.mjs, fixtures/phase12.mjs) and that every test name fragment matches a test that ran.
// Adding a rule? Add it here with its code or test: a rule with neither fails the test suite.
export const SAFEGUARDS = [
  { area: 'Deterministic datasets', rule: 'the same definition and seed always build the same question; generated data change with the seed; published data never depend on it',
    codes: [], tests: ['building twice gives identical output', 'changing the seed changes the data', 'published data don\'t depend on the seed'] },
  { area: 'Explicit physics', rule: 'models are built only from vetted laws with checked units, stated assumptions and causes of scatter; noise-free data recover the parameters',
    codes: ['physics-meta', 'physics-units', 'physics-range', 'physics-magnitude', 'physics-inversion'], tests: ['law '] },
  { area: 'Independent audit', rule: 'every dataset is re-derived from first principles without the generator\'s physics; published data unbiased; answers and conclusions recalculated',
    codes: ['independent-missing', 'independent-model', 'independent-data', 'independent-answer', 'independent-conclusion'], tests: ['the independent audit reads the data from the drawings'] },
  { area: 'Uncertainty', rule: 'uncertainties realistic (never below half the resolution or half a scale division), at most 2 s.f., matching decimal places, propagated by IB worst-case sums checked by differentiation; value ± uncertainty correctly rounded',
    codes: ['uncertainty', 'propagation', 'table-dp', 'asks-pm'], tests: ['propagation', 'Rounding: halves round up'] },
  { area: 'Y error bars', rule: 'only y error bars drawn; bars too short to see declared too small and stated in the caption, or none when unused; no wording about bars that aren\'t drawn; every drawn bar visible',
    codes: ['graph-x-errorbars', 'graph-errorbar', 'graph-errorbar-hidden', 'graph-errorbar-text'], tests: ['P1: error bars hidden under the markers', 'Some error bars hidden'] },
  { area: 'Graph and table selection', rule: 'a table only when it serves a purpose; data shown only as a graph or instrument image declare tableless and every column is readable from a figure; points left off a graph come with a Plot part',
    codes: ['table-header'], tests: ['Row labels', 'Omitted point without a Plot part'] },
  { area: 'Observational data', rule: 'observational data declare whether they are simulated; simulated observations say so in the question',
    codes: [], tests: ['T9:'] },
  { area: 'Published data', rule: 'published values match the source and either follow a model within a stated tolerance or are declared observed with a reason',
    codes: ['catalogue'], tests: ['Observed values', 'T10:'] },
  { area: 'Provenance', rule: 'published data name their source column and definition and match a stored copy of the source (checksum), with declared scale and offset conversions',
    codes: [], tests: ['T10: a published value that differs from the source is an error', 'Source offset'] },
  { area: 'Graph validation', rule: 'graphs are read back from the SVG: axes, ticks, points, traces, fit and model lines, reference lines, shaded areas, instrument scales; every value read lies on the axes',
    codes: ['graph-point', 'graph-axis', 'graph-fit', 'graph-read', 'scale-read'], tests: ['T3:'] },
  { area: 'Context diversity', rule: 'context families and objects declared; repetition within a batch or overuse in the bank is a diversity warning that blocks batch acceptance unless waived',
    codes: [], tests: ['T1:', 'an unwaived diversity warning blocks acceptance'] },
  { area: 'Data regularity', rule: 'measured data may not be cleaner or more regular than the declared measurement (equal steps, too little scatter, exact ratios, repeated digits)',
    codes: ['regular-data'], tests: ['T2:'] },
  { area: 'Mark-scheme leakage', rule: 'no answer value, unit, relationship or conclusion visible before the part that asks for it; every number traceable; typed answers come from results',
    codes: ['giveaway', 'asks-unit', 'text-number', 'answer-source', 'answer', 'markscheme-value'], tests: ['T4:'] },
  { area: 'Student-facing vs internal data', rule: 'uncertainties no part uses stay internal (no ± in the table, no bars, no wording) but still drive validation; tableless data are validated on the internal table; the preview never reaches production',
    codes: [], tests: ['showUncertainty: false', 'errorBars "none"', 'an unreviewed dataset is AUTO-VALIDATED and preview only'] },
  { area: 'Claims and verdicts', rule: 'every conclusion a question asks for is checked against the data with a margin students\' own lines can\'t reverse',
    codes: ['claim', 'claim-verdict', 'claim-anomaly', 'prediction'], tests: [] },
  { area: 'Review and approval states', rule: 'reviews in order; TEACHER-REVIEWED and APPROVED name a person; only APPROVED, unchanged datasets are published; any change to a reviewed dataset breaks the freeze; batch acceptance never records TEACHER-REVIEWED',
    codes: [], tests: ['Review gate:', 'a reworded reviewed dataset fails the freeze', 'an APPROVED dataset that changed is not published', 'batch acceptance never records TEACHER-REVIEWED'] },
];
