// Builds the Science news page (news.html) and the home-page panel's data (news/latest.json)
// from the stored stories (news/archive-YYYY.json), leaving out any listed in news/hidden.json.
//   node tools/news/build.mjs
// The collector runs this after adding a story, and GitHub runs it when news/hidden.json changes.
// tools/check.mjs reports an error if either file is out of date. Never edit the two files by hand.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROOT, NEWS_DIR, LATEST_COUNT, CATEGORIES, readTopics, loadArchive, loadHidden, isHidden } from './news-lib.mjs';

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const dateText = (iso) => new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });
const monthText = (iso) => new Date(iso).toLocaleDateString('en-GB', { month: 'long', year: 'numeric', timeZone: 'UTC' });
const possessive = (name) => (/s$/.test(name) ? `${name}’` : `${name}’s`);
const newestFirst = (a, b) => b.featuredAt.localeCompare(a.featuredAt) || b.score - a.score;

function card(s, topics) {
  const [label, icon] = CATEGORIES[s.category];
  const headline = s.linkStatus === 'gone'
    ? `${esc(s.title)} <span class="news-gone">(the original article is no longer online)</span>`
    : `<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}<span class="visually-hidden"> (opens ${esc(possessive(s.source.name))} article in a new tab)</span></a>`;
  const links = s.topics.map((id) => {
    const t = topics.get(id);
    return `<a href="themes/${id.replace('.', '').toLowerCase()}.html">${id} ${esc(t.title)}</a>${t.hl ? ' <span class="tag hl">HL</span>' : ''}`;
  }).join(', ');
  return `      <article class="news-card" id="${s.id}">
        <div class="news-tagline"><svg class="cat-icon news-icon" viewBox="0 0 40 40" aria-hidden="true" focusable="false">${icon}</svg><span class="cat-label">${label}</span></div>
        <h3>${headline}</h3>
        <p class="news-summary">${esc(s.summary)}</p>
        <p class="news-ai">Summary written automatically with AI, from ${esc(possessive(s.source.name))} article.</p>
        <p class="news-meta">${esc(s.source.name)} · <time datetime="${s.publishedAt.slice(0, 10)}">${dateText(s.publishedAt)}</time></p>
        <p class="news-topics">In the course: ${links}</p>
      </article>`;
}

export function buildOutputs() {
  const topics = new Map(readTopics().map((t) => [t.id, t]));
  const hidden = loadHidden();
  const stories = loadArchive().filter((s) => !isHidden(s, hidden)).sort(newestFirst);

  const latest = {
    note: 'Generated by tools/news/build.mjs from news/archive-*.json: do not edit by hand.',
    categories: Object.fromEntries(Object.entries(CATEGORIES).map(([k, [label, icon]]) => [k, { label, icon }])),
    stories: stories.slice(0, LATEST_COUNT).map((s) => ({
      id: s.id, title: s.title, url: s.url, source: s.source.name, summary: s.summary, category: s.category,
      topics: s.topics, publishedAt: s.publishedAt, linkStatus: s.linkStatus,
    })),
  };

  const months = [];
  for (const s of stories) {
    const m = monthText(s.featuredAt);
    if (months.at(-1)?.[0] !== m) months.push([m, []]);
    months.at(-1)[1].push(s);
  }
  const body = months.length
    ? months.map(([m, list]) => `    <h2 class="news-month">${m}</h2>\n    <div class="news-list">\n${list.map((s) => card(s, topics)).join('\n')}\n    </div>`).join('\n\n')
    : '    <p class="news-empty">The first stories will appear here soon.</p>';

  const description = 'Recent discoveries in physics and space science, each with a short summary and links to the parts of the IB DP Physics course they connect to.';
  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Science news · Mr Silkstone's Physics</title>
  <meta name="description" content="${description}">
  <link rel="canonical" href="https://physics.silkstone.xyz/news.html">
  <link rel="icon" href="favicon.svg" type="image/svg+xml">
  <link rel="icon" href="favicon-32.png" sizes="32x32" type="image/png">
  <link rel="apple-touch-icon" href="apple-touch-icon.png">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Mr Silkstone's Physics">
  <meta property="og:title" content="Science news · Mr Silkstone's Physics">
  <meta property="og:description" content="${description}">
  <meta property="og:url" content="https://physics.silkstone.xyz/news.html">
  <meta property="og:image" content="https://physics.silkstone.xyz/images/social-card.png">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="stylesheet" href="css/style.css">
  <script defer src="js/site.js"></script>
</head>
<body data-root="" data-section="news">
  <header id="site-header"></header>
  <main>
    <!-- Generated by tools/news/build.mjs from news/archive-*.json: don't edit this page by hand. -->
    <h1>Science news</h1>
    <p class="lead">Recent discoveries in physics and space science, and where they connect to the course. A new story is added on Mondays, Wednesdays and Fridays.</p>
    <p class="news-note">Each summary is written automatically by AI from the publisher’s article, so details may be simplified or missed. Click the headline to read the original. If something looks wrong, please <a href="about.html#contact">tell me</a>.</p>

${body}
  </main>
  <footer id="site-footer"></footer>
</body>
</html>
`;
  return { latest: JSON.stringify(latest, null, 2) + '\n', html };
}

export function writeOutputs() {
  const { latest, html } = buildOutputs();
  fs.mkdirSync(NEWS_DIR, { recursive: true });
  fs.writeFileSync(path.join(NEWS_DIR, 'latest.json'), latest);
  fs.writeFileSync(path.join(ROOT, 'news.html'), html);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeOutputs();
  console.log('Wrote news.html and news/latest.json.');
}
